# Generated by Django 6.0.1 on 2026-02-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("presentations_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=32)),
                ("stage", models.CharField(blank=True, max_length=64, null=True)),
                ("percent", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "presentation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="presentations_app.presentation"),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
